### ISSUE TITLE
Vocabulary card list

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **a list of vocabulary cards** 
so that **I can train my vocabulary knowledge.** 

## Description (Text, Scribble, Wireframe, Design)
* Vertically scrolling list of cards
* One card consists of an image, a headline and a word category badge:
<img width="385" alt="Bildschirmfoto 2020-03-01 um 23 52 32" src="https://user-images.githubusercontent.com/17109650/75635636-06b95080-5c18-11ea-908a-f3b60600c1a7.png">

## Acceptance criteria
- [x] Cards scroll vertically
- [x] Each card shows the right image, headline and badge for its category (noun, verb or adjective)
- [x] Cards without an image have a default image placeholder

## Tasks
- [x] Collect dummy images and add them to image folder
- [x] Create image placeholder and add it to the image folder
- [x] Create a cards.json file with dummy data for the first cards
- [ ] Write tests (test for badge colour logic to be added)
- [x] Create card component
- [x] Styling
- [x] Add PropTypes
- [ ] Add component to Storybook
- [x] Test with a few cards on mobile and desktop, in FF, Chrome and Safari

## Size
Medium
