### ISSUE TITLE
Make vocabulary cards expandable

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/capstone-project#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **to expand a vocabulary card** 
so that **I can see the translation and check if I knew it.** 

## Description (Text, Scribble, Wireframe, Design)
- Each card expands on click on "See Translation" button and shows additional information: translation, button to play audio of translation and several options to close the expanded view (close button, back link and closing cross)
<img width="407" alt="Bildschirmfoto 2020-03-01 um 23 53 40" src="https://user-images.githubusercontent.com/17109650/75635697-7deee480-5c18-11ea-8057-7cca76ba3292.png">
<img width="392" alt="Bildschirmfoto 2020-03-01 um 23 38 53" src="https://user-images.githubusercontent.com/17109650/75635385-e38da180-5c15-11ea-953c-721783668d59.png">

## Acceptance criteria
- [x] Each card shows a "See Translation" button
- [x] On click on the button, the button changes its colour and the card expands
- [ ] Card expansion is animated
- [x] Expanded card shows all elements defined in description
- [x] On click on audio button, the audio of the respective word is played
- [x] On click on close button, the card shrinks again
- [x] On click on back link, the card shrinks again
- [x] On click on closing cross, the card shrinks again
- [x] When the card is closed, the user gets back to the position in the card list where he was before expanding the card

## Tasks
- [x] Add audio files and translations to cards.json file as dummy data for first static cards
- [ ] Write tests
- [x] Create button component
- [x] Extend and split card component and add a hook for onClick event
- [x] Styling and animation
- [x] Update component in Storybook
- [x] Test with a few cards on mobile and desktop, in FF, Chrome and Safari

## Size
Medium
