### ISSUE TITLE
Create new vocabulary cards

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/capstone-project#29]
## Value statement - a requirement, not a solution
As a **user** 
I need **to enter data for new vocabulary cards into a form and submit it** 
so that **I can create new vocabulary cards to learn** 

## Description (Text, Scribble, Wireframe, Design)
* By click on a button below the cards, a form can be opened in an overlay:
![Bildschirmfoto 2020-03-06 um 11 21 12](https://user-images.githubusercontent.com/17109650/76075129-be45be00-5f9c-11ea-9814-cfd6e7dd48dc.png)

* The form contains the following elements:
-- image upload
-- vocabulary title
-- translation
-- word category (verb, noun or adjective)
-- audio file
-- submit button
-- closing icon, closing button and back link
* Form data is submitted and saved to local storage
* Cards are added to vocabulary list
<img width="344" alt="Bildschirmfoto 2020-03-06 um 12 28 19" src="https://user-images.githubusercontent.com/17109650/76079907-05847c80-5fa6-11ea-9b10-1fba81170345.png">

## Acceptance criteria
- [x] A button is shown below the card slider
- [x] On click on button, a form opens in a modal
- [x] The form contains all elements specified above
- [x] The form can be closed and the user will get back to the same place where he was before opening the form
- [ ] Form validation & error handling?
- [x] Form can be submitted on click on submit button
- [x] After submit, the form is closed, the user is redirected to the card list and a new card with the submitted information is shown in the first position of the card list
- [x] On page reload, the card still shows

## Tasks
- [ ] Write tests
- [x] Extend button component
- [x] Create form component
- [x] Styling and animation
- [x] Save submitted data to local storage
- [x] Add component to Storybook
- [ ] Test with different form input on mobile and desktop, in FF, Chrome and Safari

## Size
Large
