### ISSUE TITLE
Vocabulary card slider

### ISSUE THREAD

**Issue by carinamenke** [carinamenke/capstone-project#3]
## Value statement - a requirement, not a solution
As a **user** 
I need **to swipe through my vocabulary cards** 
so that **I can have a look at my cards in a comfortable way.** 

## Description (Text, Scribble, Wireframe, Design)
* The basic list of cards should be transformed into a slider:
<img width="378" alt="Bildschirmfoto 2020-03-02 um 00 06 01" src="https://user-images.githubusercontent.com/17109650/75635873-f99d6100-5c19-11ea-90b9-311a96cb1043.png">

## Acceptance criteria
- [x] It is possible to swipe horizontally through list of cards

## Tasks
- [ ] Write tests
- [x] Extend card component 
- [x] Styling and animation
- [x] Update component in Storybook
- [x] Test with a few cards on mobile and desktop, in FF, Chrome and Safari

## Size
Medium
